library(circlize)
setwd("~/Your/Path")
circo_initial <- read.table(file.choose(), header = FALSE)
circo_final <- read.table(file.choose(), header = FALSE)
colnames(circo_initial)<- c('chr','start','end','value')
colnames(circo_final)<- c('chr','start','end','value')
bed_list<- list(circo_initial,circo_final)
pal <- choose_palette()
mypal<- c(pal(2))
write.table(mypal, file = "hexcodes.txt", sep = "\t",
            row.names = TRUE, col.names = NA)
circos.clear()
png(filename = "NF2007VSNF2010.png", width = 1280, height = 1001, res = 175)
circos.initializeWithIdeogram(chromosome.index = c("chr1", "chr2","chr3","chr4","chr5","chr6","chr7","chr8","chr9","chr10","chr11","chr12","chr13","chr14","chr15","chr16","chr17","chr18","chr19","chr20","chr21","chr22","chrX"))
circos.genomicRainfall(bed_list,ylim = c(-1,8), pch = 20, cex = 0.3, col = mypal) 
circos.genomicDensity(bed_list[[1]], col = mypal[1], track.height = 0.1)
circos.genomicDensity(bed_list[[2]], col = mypal[2], track.height = 0.1)
legend("bottomleft", pch = 20, legend = c('NF2007_20','NF2010_12'), col = mypal) 
dev.off()

